### ISSUE TITLE
App  Crashes.

### ISSUE THREAD

**Issue by YYYSSSHHH** [billthefarmer/notes#18]
**Environment Info：**
APK Version: 1.15 (115)
Android simulator version: 6.0.1
**Repro Steps：**
1.Write something in a notes. 
2.Click the "System back" button.
3.Click the "DISCARD"button (or "Save" button) and then the app will crash.
![Nodes](https://user-images.githubusercontent.com/55122523/126054506-db7909a3-7004-4d04-9ffa-06abbe79f413.png)

**Do you judge this as a defect? Thank you for your reply.**

**Comment by billthefarmer** [comment]
The app generates a traceback if you do this more than once because a second dialog is triggered by attempting to overwrite an existing file. However android does not report an app crash. As the first dialog calls `super.onBackPressed()`  after calling `saveNote()`, the app quits, leaving an orphan 'Overwrite' dialog. This **does not** happen when pressing 'Discard'. As android does not report a problem, I have no intention of attempting to 'fix' this. The log file of a real device, as opposed to an emulator, is full of tracebacks and errors from parts of the android system.

**Comment by YYYSSSHHH** [comment]
https://user-images.githubusercontent.com/55122523/126062356-3e221a46-ade1-4b5f-933d-ce420c996384.mp4

This **does** happen when pressing 'Discard'.   The reason for the crash may be that I used a simulator

**Comment by billthefarmer** [comment]
I checked this on a Moto G running Android 7.1.2, there is minimal output related to the app, no traceback.
```shell
07-18 10:56:44.387   652  1057 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=org.billthefarmer.notes/.Notes bnds=[536,819][712,1088] (has extras)} from uid 10026 on display 0
07-18 10:56:44.733   652   727 I ActivityManager: Displayed org.billthefarmer.notes/.Notes: +308ms
```
An on an emulator running Android 10, there is more output, but no traceback.
```shell
07-18 11:03:22.939  1850  2833 I ActivityTaskManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=org.billthefarmer.notes/.Notes bnds=[855,1475][1124,1900]} from uid 10080
07-18 11:03:23.064  1850  1878 I ActivityManager: Start proc 3220:org.billthefarmer.notes/u0a107 for activity {org.billthefarmer.notes/org.billthefarmer.notes.Notes}
07-18 11:03:23.260  3220  3220 W RenderThread: type=1400 audit(0.0:8): avc: denied { write } for name="property_service" dev="tmpfs" ino=8410 scontext=u:r:untrusted_app_27:s0:c107,c256,c512,c768 tcontext=u:object_r:property_socket:s0 tclass=sock_file permissive=0 app=org.billthefarmer.notes
07-18 11:03:23.645  1850  1878 I ActivityManager: Start proc 3254:com.android.webview:sandboxed_process0:org.chromium.content.app.SandboxedProcessService0/u0ai9000 for  {org.billthefarmer.notes/org.chromium.content.app.SandboxedProcessService0}
07-18 11:03:23.712  1625  1625 E Layer   : [Surface(name=AppWindowToken{38e0f6c token=Token{8b7e01f ActivityRecord{2687be u0 org.billthefarmer.notes/.Notes t39}}})/@0xe7d9ff - animation-leash#0] No local sync point found
07-18 11:03:23.712  1625  1625 E Layer   : [Surface(name=AppWindowToken{38e0f6c token=Token{8b7e01f ActivityRecord{2687be u0 org.billthefarmer.notes/.Notes t39}}})/@0xe7d9ff - animation-leash#0] No local sync point found
07-18 11:03:24.734  1850  1876 I ActivityTaskManager: Displayed org.billthefarmer.notes/.Notes: +1s785ms
07-18 11:03:24.895  3220  3243 I chatty  : uid=10107(org.billthefarmer.notes) RenderThread identical 1 line
07-18 11:03:24.936  3220  3285 I chatty  : uid=10107(org.billthefarmer.notes) Chrome_InProcGp identical 2 lines
07-18 11:03:49.624  3220  3243 I chatty  : uid=10107(org.billthefarmer.notes) RenderThread identical 2 lines
07-18 11:03:49.940  1850  2833 E InputDispatcher: Window handle Window{28d064d u0 org.billthefarmer.notes/org.billthefarmer.notes.Notes} has no registered input channel
07-18 11:09:12.217  1850  1970 E ClipboardService: Denying clipboard access to org.billthefarmer.notes, application is not in focus neither is a system service for user 0
```
There is no orphaned dialog in this case, because pressing any button or touching the app display around the dialog dismisses the dialog before anything else happens.
